### ISSUE TITLE
Color incorrect Dashboard, Here is your analytic details 

### ISSUE THREAD

**Issue by NguyenTrang091296** [aesirxio/pim-app#12]
![image](https://user-images.githubusercontent.com/39818849/210474546-e3fdac9c-4c22-4102-89da-89f65abf2165.png)
Small text in Product’s State (publish, unpublish, draft, archived, waiting approved, trash)
![image](https://user-images.githubusercontent.com/39818849/210474588-717561b9-2d79-4a7e-8bd8-bb22839430fb.png)
![image](https://user-images.githubusercontent.com/39818849/210474630-8ff3456e-ad15-44b1-9add-7d03972acd17.png)

**Comment by vietredweb** [comment]
It got fixed in this PR chị @NguyenTrang091296  https://github.com/aesirxio/pim-app/issues/11
