### ISSUE TITLE
Product - Color

### ISSUE THREAD

**Issue by NguyenTrang091296** [aesirxio/pim-app#14]
![image](https://user-images.githubusercontent.com/39818849/210474856-d95b4058-a4d4-4fd8-ad6f-2896f17e2c2c.png)
![image](https://user-images.githubusercontent.com/39818849/210474901-d84f7ea3-08b5-4a6d-a51f-c86d418329dd.png)
Change the color, background-color when user going on the All product tab menu item 
![image](https://user-images.githubusercontent.com/39818849/210475032-92aabf06-792d-4748-886f-605ef8a50ed5.png)

**Comment by vietredweb** [comment]
It got fixed in this PR chị @NguyenTrang091296  https://github.com/aesirxio/pim-app/issues/11
