### ISSUE TITLE
Product - Add function filter by dates

### ISSUE THREAD

**Issue by NguyenTrang091296** [aesirxio/pim-app#15]

**Comment by lklong709** [comment]
waiting API.

**Comment by nhatvippro** [comment]
@lklong709 this api is ready on dev and pass QA, plss progess

**Comment by VanTrieuThanh** [comment]
![Screenshot from 2023-02-17 10-59-02](https://user-images.githubusercontent.com/44457418/219546422-858f45d3-157c-4126-881f-e3f39d41c192.png)
has update
