### ISSUE TITLE
Update language for DAM

### ISSUE THREAD

**Issue by lklong709** [aesirxio/pim-app#211]

**Comment by huynhngocgiau** [comment]
I can't test, I will check after this problem is fixed
![image](https://user-images.githubusercontent.com/79819354/219547912-fc210cf6-8f41-436e-a6d9-cac0f1643e5b.png)

**Comment by huynhngocgiau** [comment]
Thai

![image](https://user-images.githubusercontent.com/79819354/220295753-14f36c8d-c253-4a20-a0d4-bf3592891686.png)
