### ISSUE TITLE
Dark mode - Product filter date change the color text

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/pim-app#213]
![Image](https://user-images.githubusercontent.com/44457418/219546954-41465e3c-3636-4c6b-83b8-0b2a481d8853.png)

**Comment by lklong709** [comment]
pr for QA: https://github.com/aesirxio/pim-app/pull/237

**Comment by VanTrieuThanh** [comment]
has update 
![image](https://user-images.githubusercontent.com/44457418/221784021-64f0e4b4-0d88-468d-af66-296a58345f46.png)
but the background #1A2226  not same design #0F1314
![Screenshot from 2023-02-28 14-35-13](https://user-images.githubusercontent.com/44457418/221785495-f7152b1a-5735-4192-a262-d6c12a5b8b99.png)
border: 1px solid #3E545E not same design #dedede
![Screenshot from 2023-02-28 15-01-23](https://user-images.githubusercontent.com/44457418/221790659-9c5a3f20-7c22-486d-9b18-6a65946fc960.png)
remove the start - end date 
![image](https://user-images.githubusercontent.com/44457418/221791072-7e5bc150-d97f-423b-a05d-c03923e0916c.png)

**Comment by VanTrieuThanh** [comment]
it has update on my local
