### ISSUE TITLE
UI - Style filter date

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/pim-app#214]
current style 
![Image](https://user-images.githubusercontent.com/44457418/219548207-568369a4-3b32-4e5e-95ce-8f664cf2d9c5.png)

chị @TrucNguyenx help me show the design for filter date

**Comment by TrucNguyenx** [comment]
Here is the design of filter day 
![image](https://user-images.githubusercontent.com/118497336/219551724-fd91a6ec-71f0-4743-8609-8427893eb1b7.png)

-> But I talk to Viet to custom it from plugin so it will be like this
(This from BI platform, please adapt for all) @VanTrieuThanh @vietredweb
![image](https://user-images.githubusercontent.com/118497336/219551902-6572ff86-c304-4437-a3e9-49f6fe93f7fd.png)

**Comment by vietredweb** [comment]
https://github.com/aesirxio/bi-app/pull/58/files
Please follow this a @lklong709

**Comment by lklong709** [comment]
pr for QA: https://github.com/aesirxio/pim-app/pull/237

**Comment by VanTrieuThanh** [comment]
has update ![image](https://user-images.githubusercontent.com/44457418/221783822-c28c3bb6-32ce-46b7-8e96-2b303d0b9e2f.png)
![image](https://user-images.githubusercontent.com/44457418/221783896-e369fc85-9a1f-4624-a4c8-561b135f25f3.png)

**Comment by VanTrieuThanh** [comment]
but remove the range date 
![image](https://user-images.githubusercontent.com/44457418/221792252-5e7868bb-2f31-43cf-9a29-fc553a615c53.png)
change the background range date select design #F0F3FB on the dev site rgba(59, 122, 181, 0.2);
change color text when hover 
![image](https://user-images.githubusercontent.com/44457418/221792887-0537c4d0-70cf-4d5c-bead-7468f55f9de0.png)
Change color text 
![image](https://user-images.githubusercontent.com/44457418/221793631-cb7b4616-3262-43f9-b9f3-795ce0b78c08.png)
Change the solid between 2 month 1px solid #e9e9e9;
![image](https://user-images.githubusercontent.com/44457418/221794270-5ab955ee-4718-4683-9795-6379ec0a3bf5.png)

**Comment by VanTrieuThanh** [comment]
Change the solid between 2 month 1px solid #e9e9e9;
![image](https://user-images.githubusercontent.com/44457418/223007974-0dbecfec-55a4-4750-b40d-a43d4a1c3653.png)

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/223631463-84655db2-cee9-4e85-87e0-bcc9951c2712.png)
