### ISSUE TITLE
Login app - Change the basic style 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/pim-app#22]
on the dev site app
Compare with design DAM to clone about the style
https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=5290%3A29850&t=jdUBSTjC1zu0f0ws-0
Remember change text for each project
![image](https://user-images.githubusercontent.com/44457418/210479900-9fae265c-4c0f-48c8-8aae-f6496c0fd22c.png)

**Comment by NguyenTrang091296** [comment]
"SIGN IN" button have font-weight:700
"Remember me" have color: #000000;
Asterisk have color: #C60202;
Forgot password? have color: #3B7AB5
Welcome text have color: #0A083B and font-size: 32px
Change text 'Sign In with SSO' to 'Sign in with SSO'
'OR' have color:#0A021C  font-weight: 500

Please help me fix cc @vietredweb

**Comment by VanTrieuThanh** [comment]
![image](https://user-images.githubusercontent.com/44457418/211997624-fcaa3548-47d3-4423-af06-e7a8a0fdd11e.png)
active icon not same design 
![image](https://user-images.githubusercontent.com/44457418/211996363-7012bd32-9a6d-4a4a-95da-6a8315dfa940.png)
Field Email, password is height 48px 
![image](https://user-images.githubusercontent.com/44457418/211996902-0b1f465a-6cd5-4a3e-a38c-aafc8726fd74.png)
padding 
![image](https://user-images.githubusercontent.com/44457418/211997036-8c36e389-c943-4bcc-ac3b-bb5dcda21e5a.png)
![image](https://user-images.githubusercontent.com/44457418/211997191-68a99a04-c029-4bf8-b099-84d47dfd8136.png)
![image](https://user-images.githubusercontent.com/44457418/211997295-a0c2b40c-7cd6-4b53-92dc-25cba40659c2.png)
Let compare with https://www.figma.com/file/m0VZCJPKKj8uGOfZReXMYR/AesirX-Platform?node-id=5290%3A29850&t=8By69cl0YwTJyep1-0 em

**Comment by VanTrieuThanh** [comment]
![image](https://user-images.githubusercontent.com/44457418/212254996-be130334-f889-45c1-8de7-33bcfeaeadad.png)
![image](https://user-images.githubusercontent.com/44457418/212255030-bcd4c11d-e045-4df5-8a98-80aa58b47e83.png)
![image](https://user-images.githubusercontent.com/44457418/212255214-811a565a-9d34-4d98-a576-b815b9c75756.png)
![image](https://user-images.githubusercontent.com/44457418/212255680-7978e956-aebb-4894-bb04-28c735f86d87.png)
