### ISSUE TITLE
The icon must be aligned center

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/pim-app#231]
![image](https://user-images.githubusercontent.com/30283123/220598752-edc8e611-6463-42a9-9020-b1789c53d009.png)

**Comment by lklong709** [comment]
QA: https://github.com/aesirxio/pim-app/pull/240

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/222068844-5167392e-645a-4bd6-b964-906a91374a89.png)
