### ISSUE TITLE
The layout of button is broken

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/pim-app#232]
1. Launch the app
2. login and go to Field group
3.At description, click at image logo, then click on create folder 

 Actual output:
![image](https://user-images.githubusercontent.com/30283123/220600781-3e338660-41ee-4f85-94d2-5f9353b5b566.png)

**Comment by VanTrieuThanh** [comment]
the layout has change 
![image](https://user-images.githubusercontent.com/44457418/222047802-e6aeecef-b93e-492f-b1e5-0f9ac3adc8ab.png)
