### ISSUE TITLE
Range date - Change icon dropdown to calendar

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/pim-app#233]
![Image](https://user-images.githubusercontent.com/44457418/220845495-f2f3f0ca-8175-456a-a714-177b9124a6e9.png)

**Comment by lklong709** [comment]
QA: https://github.com/aesirxio/pim-app/pull/241

**Comment by VanTrieuThanh** [comment]
has update but icon not same design 
![image](https://user-images.githubusercontent.com/44457418/222080282-21a8b0bb-3012-4ff9-aa9c-c41d4786f013.png)

**Comment by VanTrieuThanh** [comment]
Icon has change same design 
![image](https://user-images.githubusercontent.com/44457418/222102869-fe0abc1c-3b86-4c87-a387-afc7fa17182f.png)
