### ISSUE TITLE
Witdth of dropdown should be in unity

### ISSUE THREAD

**Issue by thaoredweb** [aesirxio/pim-app#234]
Witdth of dropdown should be in unity (DAM intergration)

![Image](https://user-images.githubusercontent.com/30283123/220862843-fec525cc-c50b-49ed-bc35-b28bd99727f4.png)
reference Long PR
https://github.com/lklong709/mcms-app/commit/a4f0ae2b438b28ab9c2eb18b47455a0725bf5381

**Comment by VanTrieuThanh** [comment]
it has update 
![image](https://user-images.githubusercontent.com/44457418/222045409-6c0a27ee-649c-43de-95a2-448aad02ce0c.png)
