### ISSUE TITLE
Translate Denmark for app

### ISSUE THREAD

**Issue by huynhngocgiau** [aesirxio/pim-app#235]
![image](https://user-images.githubusercontent.com/79819354/221091007-26adad57-d772-4306-87cc-1441db47c8f8.png)
![image](https://user-images.githubusercontent.com/79819354/221091249-4b4a916f-a8bf-4f16-a5bd-5513d396c676.png)
![image](https://user-images.githubusercontent.com/79819354/221091402-cf6e64e1-7a06-4906-8925-725b44488195.png)
![image](https://user-images.githubusercontent.com/79819354/221091967-b7296650-e75d-411c-88eb-46685c703a61.png)
![image](https://user-images.githubusercontent.com/79819354/221092547-1f5cecb7-5459-47ed-97cb-8a42e2fa7633.png)
![image](https://user-images.githubusercontent.com/79819354/221092845-ba8d4703-b28e-43f1-be36-d5566a0bcaa6.png)
![image](https://user-images.githubusercontent.com/79819354/221093123-f80fc10b-d875-49a9-b7ac-d8f8735dfd8d.png)

**Comment by lklong709** [comment]
QA PR: https://github.com/aesirxio/pim-app/pull/245

**Comment by huynhngocgiau** [comment]
please check again a @lklong709 
![image](https://user-images.githubusercontent.com/79819354/222623621-190be1df-6f81-4503-b617-a2be1b70edbc.png)

**Comment by huynhngocgiau** [comment]
please check again 
![image](https://user-images.githubusercontent.com/79819354/222656888-7b81e8c6-8cb1-412e-8b08-f56a5d1ad9be.png)

**Comment by lklong709** [comment]
please check again, make sure you clear all cookie and cache.

**Comment by huynhngocgiau** [comment]
has updated
![image](https://user-images.githubusercontent.com/79819354/222673681-dd4d4c1f-040f-4278-9799-3f7658e612a9.png)
