### ISSUE TITLE
UI - Product/Add new/ Publish options

### ISSUE THREAD

**Issue by huynhngocgiau** [aesirxio/pim-app#238]
Please check design again 
1. Add more space between elements 
2. Add icon for Last Modified
3. Background color 

![image](https://user-images.githubusercontent.com/79819354/221782418-e38f34ba-30eb-4abe-95a1-f2a8d7651d7d.png)

**Comment by lklong709** [comment]
@TrucNguyenx please help me confirm the background of input that can only read.

**Comment by lklong709** [comment]
@huynhngocgiau 
1. Please help me explain more detail what you really want to fix and confirm with Truc about that.

**Comment by lklong709** [comment]
QA repo: https://github.com/aesirxio/pim-app/pull/242

**Comment by TrucNguyenx** [comment]
@lklong709 confirm it only read for now cc @huynhngocgiau

**Comment by VanTrieuThanh** [comment]
![image](https://user-images.githubusercontent.com/44457418/222106522-3d01305a-3af2-4d16-8948-413144077ef4.png)
background not update 
![image](https://user-images.githubusercontent.com/44457418/222109892-b08540cb-b3be-4977-961d-51464c7684fa.png)

**Comment by lklong709** [comment]
@VanTrieuThanh i am already confirm with @TrucNguyenx about background of readonly field
