### ISSUE TITLE
Field Range date - Change same design 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/pim-app#243]
design 
![image](https://user-images.githubusercontent.com/44457418/222103193-5ca9bfaa-2ed9-40fd-9259-ec706adf1772.png)
Dev site 
![image](https://user-images.githubusercontent.com/44457418/222103550-e421d0e3-82dd-4477-a607-51f257f6ed34.png)

Expected result:
- First view show All date and icon calendar 
- When select the date will show the start - end

**Comment by lklong709** [comment]
QA: https://github.com/aesirxio/pim-app/pull/237

**Comment by VanTrieuThanh** [comment]
![image](https://user-images.githubusercontent.com/44457418/222652411-a7af4160-19f1-4dbf-8371-3484380ef395.png)
code failing anh ơi

**Comment by VanTrieuThanh** [comment]
change color prev/next icon - #222328
![image](https://user-images.githubusercontent.com/44457418/222661308-e49d85fe-7096-40e2-bb33-f9cdef2ca97e.png)
change border-radius 4px
![image](https://user-images.githubusercontent.com/44457418/222662919-94742a3f-cec6-4cc4-a26e-4d07f080c1a8.png)
Missing line between 2 month - #E9E9E9
![image](https://user-images.githubusercontent.com/44457418/222664018-cd692737-a7ee-4d83-982f-da3cd866d283.png)

**Comment by VanTrieuThanh** [comment]
help me change it again 
![image](https://user-images.githubusercontent.com/44457418/223006782-0fe2652a-b1db-4844-abcc-c63c7bec3ad5.png)

**Comment by huynhngocgiau** [comment]
Please check again a @lklong709 
Background: #EBF3F6
![image](https://user-images.githubusercontent.com/79819354/223632902-3e5c9889-37e5-4889-8d17-229324524c33.png)

**Comment by VanTrieuThanh** [comment]
has update 
![image](https://user-images.githubusercontent.com/44457418/223655509-d0c23803-b266-46fb-9c55-c62c309cce34.png)
