### ISSUE TITLE
List screen - Table should be striped

### ISSUE THREAD

**Issue by NguyenTrang091296** [aesirxio/pim-app#44]
Expected result:
![image](https://user-images.githubusercontent.com/39818849/210526501-6e16b9ff-321c-4da6-a635-58cc6b0262fd.png)

**Comment by VanTrieuThanh** [comment]
has update on the dev site 
![image](https://user-images.githubusercontent.com/44457418/211994020-0c8ba1ea-dfa1-412d-a03d-af5c0e38c812.png)
