### ISSUE TITLE
Dashboard - Adjust spacing

### ISSUE THREAD

**Issue by TrucNguyenx** [aesirxio/pim-app#53]
Adjust spacing

![Image](https://user-images.githubusercontent.com/118497336/210738017-b16c6139-75f5-4811-9e81-9de724a807d4.png)

**Comment by VanTrieuThanh** [comment]
help me check the height 
![image](https://user-images.githubusercontent.com/44457418/212011417-eb6d4bde-336d-4159-9119-bcd20df3c5da.png)
