### ISSUE TITLE
Left menu - Add item 'DAM storage' 

### ISSUE THREAD

**Issue by NguyenTrang091296** [aesirxio/pim-app#59]
Expected result:
![image](https://user-images.githubusercontent.com/39818849/210932477-a91e9f00-d03b-43be-95f1-050ad2d6a7e2.png)

**Comment by kakahuy113** [comment]
@vietredweb please help me test for storage

**Comment by vietredweb** [comment]
![Image](https://user-images.githubusercontent.com/53933634/215405976-4bb05dda-40e0-473f-917f-22a140756bb3.png)

I got "Something went wrong" here when trying to use  `<AesirXDamStorage />` Component @kakahuy113 , can you help check here?
