### ISSUE TITLE
Edit Product/Category/Debtor group - Missing the product name 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/pim-app#63]
Product
![image](https://user-images.githubusercontent.com/44457418/211242748-ef0cf29a-4bd9-4829-bede-6a632a3173db.png)
Debtor group 
![image](https://user-images.githubusercontent.com/44457418/211251815-0cbf51d4-34a6-4e9a-a5da-14db81c951fd.png)
Category 
![image](https://user-images.githubusercontent.com/44457418/211251913-538dcfa9-9b78-4626-a07c-02ae60c41600.png)

**Comment by vietredweb** [comment]
It got fixed on #7 chị @VanTrieuThanh
