### ISSUE TITLE
Edit Price - Lost the content price field 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/pim-app#67]
Create 
![image](https://user-images.githubusercontent.com/44457418/211263528-ec3ae974-9c69-4d4c-a903-1c06949902bb.png)

the Price detail when user click on the Edit 
![image](https://user-images.githubusercontent.com/44457418/211263393-cfa49589-6bdd-4a53-b081-2c41e4ca817f.png)

**Comment by vietredweb** [comment]
It was fixed on #7 chị @VanTrieuThanh

**Comment by NguyenTrang091296** [comment]
![image](https://user-images.githubusercontent.com/39818849/212005206-15075eb3-575e-41e3-a482-1072065b1f47.png)
I checked and I see it has been fixed
