### ISSUE TITLE
Product - Missing the field just create in custom field tab 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/pim-app#72]
- Create a field item with General Information
![image](https://user-images.githubusercontent.com/44457418/211273193-bce4dc49-8de0-40f2-b4e7-4e757c1fc39d.png)
- Go to the product item detail to find the item field just create at the General Information tab - but it not exist 
![image](https://user-images.githubusercontent.com/44457418/211273787-a487ce34-b82d-4c42-b9c7-7aebe69b6c3e.png)
![image](https://user-images.githubusercontent.com/44457418/211273804-5924f503-b2e4-49e3-8916-9dee660bdaec.png)

Check more with SEO and Dimension

**Comment by vietredweb** [comment]
Can you help recheck this chị @VanTrieuThanh , I see it still working
