### ISSUE TITLE
Field group - Remove Section field 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/pim-app#74]
![image](https://user-images.githubusercontent.com/44457418/211280234-185e7f14-a8e3-4799-97d8-20d2f3290f3e.png)

**Comment by vietredweb** [comment]
Can you help recheck it chị @VanTrieuThanh ?

**Comment by vietredweb** [comment]
![image](https://user-images.githubusercontent.com/53933634/215422320-5acc8bb9-5eb4-4766-bc1f-f5a4741a859e.png)
I got this when trying to save Field Group a @devTuanTuan
