### ISSUE TITLE
Field/Field Group - Content message incorrect when user create new item 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/pim-app#76]
Field 
![image](https://user-images.githubusercontent.com/44457418/211287182-ce038c82-4182-4484-b49c-3bb3f92b3753.png)

Field Group 
![image](https://user-images.githubusercontent.com/44457418/211286040-344497f7-f140-433f-8c6f-5b968c6a1963.png)

**Comment by vietredweb** [comment]
It got fixed in #85  chị @VanTrieuThanh

**Comment by VanTrieuThanh** [comment]
@vietredweb chị check on the demo site it reload page overtime em. Can check again on it
![image](https://user-images.githubusercontent.com/44457418/212611999-e46ae4db-5b96-4878-9513-a6e657907b48.png)

**Comment by vietredweb** [comment]
It will be fix on #6 chị @VanTrieuThanh

**Comment by vietredweb** [comment]
Can you help recheck chị @VanTrieuThanh ? I fixed it

**Comment by NguyenTrang091296** [comment]
I checked and I see it work fine on dev site, please help me deploy on live site
