### ISSUE TITLE
Dark mode 

### ISSUE THREAD

**Issue by VanTrieuThanh** [aesirxio/pim-app#77]
![image](https://user-images.githubusercontent.com/44457418/211289543-41464294-b7fa-4f48-908d-d55a3c75744e.png)
Login page - After Logout
![image](https://user-images.githubusercontent.com/44457418/211289896-c8363fc7-ddda-4daa-b02d-a15b22e66963.png)

**Comment by vietredweb** [comment]
It was fixed on #79  chị @VanTrieuThanh

**Comment by NguyenTrang091296** [comment]
Hi @vietredweb please help me adjust when user logout it exit dark mode
