### ISSUE TITLE
Layout list - Color

### ISSUE THREAD

**Issue by NguyenTrang091296** [aesirxio/pim-app#86]
Column name : #8E8E8E;
Showing text: #9A9A9A;
Text on selection: #222328

![Image](https://user-images.githubusercontent.com/39818849/211533036-c0d56862-c2d0-42df-8761-810cec710144.png)

**Comment by TrucNguyenx** [comment]
After checking please follow this color, apply for all:
- Column name + Showing: #8E8E8E;
- Text on selection: #222328
